# This file was generated by FitSNAP.
# Hash: 548e6e82bd70f612c9ace1bde1e910a2

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta