# This file was generated by FitSNAP.
# Hash: cf47b9ffdf36711894b3b72829dd91ec

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta