# This file was generated by FitSNAP.
# Hash: 951ce8334ac6e2e0fd0e232c99674687

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta