# This file was generated by FitSNAP.
# Hash: a6237df29d7a0a948256c5d77e449c40

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta