# This file was generated by FitSNAP.
# Hash: b7d9f7c58e076972c0086895af6db7e1

pair_style hybrid/overlay zbl 4.0 4.8 snap
pair_coeff * * zbl 73 73
pair_coeff * * snap Ta_pot.snapcoeff Ta_pot.snapparam Ta